# Generated by Django 3.1.6 on 2021-02-25 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='title')),
                ('description', models.TextField(default='', max_length=200, verbose_name='description')),
                ('date', models.DateField(default='', verbose_name='date')),
                ('state', models.CharField(choices=[('DF', 'Draft'), ('PU', 'Public'), ('PR', 'Private')], default='DF', max_length=2, verbose_name='state')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('subscriber', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(date__gte=datetime.date(2021, 2, 25)), name='date_gte_present'),
        ),
    ]
