# Generated by Django 3.1.6 on 2021-02-20 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['dateCreated']},
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='event',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('DF', 'Draft'), ('PU', 'Public'), ('PR', 'Private')], default='DF', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
