# Generated by Django 3.1.6 on 2021-02-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210220_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateCreated',
            new_name='date',
        ),
    ]
