# Generated by Django 3.1.6 on 2021-03-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210228_0011'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='date_gte_present',
        ),
    ]
