# Generated by Django 3.1.6 on 2021-02-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210220_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['dateTime'],
            },
        ),
    ]
