# Generated by Django 3.1.6 on 2021-02-24 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210222_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(date__gte=datetime.date(2021, 2, 24)), name='date_gte_present'),
        ),
    ]
