# Generated by Django 3.1.6 on 2021-02-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210224_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('DF', 'Draft'), ('PU', 'Public'), ('PR', 'Private')], default='DF', max_length=2, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='dateTime'),
        ),
    ]
