# Generated by Django 3.1.6 on 2021-02-24 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210224_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
