# Generated by Django 3.1.6 on 2021-02-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='is_anon',
            field=models.BooleanField(default=False, help_text='allows for an "anonymous user to save username and email.', verbose_name='anonymous_user'),
        ),
    ]
